version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  web:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/post_db
    container_name: web
    build: .
    volumes:
      - .:/web
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  celery_worker:
    env_file: .env
    container_name: celery_worker
    build: .
    command: celery -A celery_worker worker --loglevel=info
    volumes:
      - .:/web
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - web
      - redis
      - rabbitmq
      - db

  celery_beat:
    build: .
    image: fastapi_celery_example_celery_beat
    command: celery -A celery_worker beat -l INFO --scheduler celery_sqlalchemy_scheduler.schedulers:DatabaseScheduler
    volumes:
      - .:/web
    env_file: .env
    depends_on:
      - web
      - redis
      - rabbitmq
      - db
