"""New Migration

Revision ID: 53a60aa8140e
Revises: aa264beccc74
Create Date: 2021-11-06 06:56:35.136010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a60aa8140e'
down_revision = 'aa264beccc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
