"""New Migration

Revision ID: 5f017ef24c94
Revises: 139577903b4c
Create Date: 2021-10-30 12:33:50.342159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f017ef24c94'
down_revision = '139577903b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
