"""New Migration

Revision ID: baa133f47afe
Revises: 7de73555113c
Create Date: 2021-10-30 12:45:03.513398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa133f47afe'
down_revision = '7de73555113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
