"""New Migration

Revision ID: e63ac23cebbf
Revises: 83b6e9b98379
Create Date: 2021-10-30 12:42:24.316746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63ac23cebbf'
down_revision = '83b6e9b98379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
